config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/profile', to: 'users#profile', as: :profile
  get 'users/:id/posts', to: 'users#user_posts', as: :user_posts

  resources :users, only: [] do
    resources :fellowships, only: [:index, :create, :destroy, :update]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"

  resources :posts do
    resources :comments
    resources :likes, only: [:create]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

  default_scope { order(created_at: :desc) }

  validates :body, length: { maximum: 140 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.create(comment_params)

    redirect_to request.referrer
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
    <article class="p-6 text-base bg-white rounded-sm dark:bg-gray-900 border-t dark:border-gray-700">
      <div class="flex justify-between items-center mb-2">
        <div class="flex items-center p-2 dark:hover:bg-gray-800 rounded-lg max-w-max">
          <%= link_to profile_path(comment.user) do %>
            <span class="flex items-center gap-2.5">
              <%= image_tag comment.user.avatar_or_url, alt: 'User Avatar', class: 'comment-avatar' %>
              <%= comment.user.username %>
            </span>
          <% end %>
        </div>
      </div>
      <p class="text-gray-500 dark:text-gray-400 break-all"><%= comment.body %></p>
      <div class="flex items-center mt-4 space-x-4">
        <button type="button"
          class="flex items-center text-sm text-gray-500 hover:underline dark:text-gray-400 font-medium">
          <svg class="mr-1.5 w-3.5 h-3.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 18">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 5h5M5 8h2m6-3h2m-5 3h6m2-7H2a1 1 0 0 0-1 1v9a1 1 0 0 0 1 1h3v5l5-5h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1Z"/>
          </svg>
          Reply
        </button>
      </div>
    </article>

app/views/comments/_form.html.erb
<section class="bg-white dark:bg-gray-900 py-8 lg:py-16 antialiased">
  <div class="max-w-2xl mx-auto px-4">
      <div class="flex justify-between items-center mb-6">
        <h2 class="text-lg lg:text-2xl font-bold text-gray-900 dark:text-white">Discussion (<%= post.comments.count %>)</h2>
    </div>
    <div class="mt-4">
      <%= form_with model: [@post, Comment.new], url: post_comments_path(@post) do |f| %>
        <div class="py-2 px-4 mb-4 bg-white rounded-lg rounded-t-lg border border-gray-200 dark:bg-gray-800 dark:border-gray-700">
          <%= f.text_area :body, class: "px-0 w-full text-sm text-gray-900 border-0 focus:ring-0 focus:outline-none dark:text-white dark:placeholder-gray-400 dark:bg-gray-800", placeholder: "Your comment here..." %>
          <%= f.hidden_field :post_id, value: @post.id %>
          <%= f.submit "Post Comment", class: "inline-flex items-center py-2.5 px-4 btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</section>