config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/profile', to: 'users#profile', as: :profile
  get 'users/:id/posts', to: 'users#user_posts', as: :user_posts

  resources :users, only: [] do
    resources :fellowships, only: [:index, :create, :destroy, :update]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"

  resources :posts do
    resources :comments
    resources :likes, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :following_users, class_name: "Fellowship", foreign_key: :followee_id, inverse_of: :followee
  has_many :followers, through: :following_users, dependent: :destroy

  has_many :followed_users, class_name: "Fellowship", foreign_key: :follower_id, inverse_of: :follower
  has_many :followees, through: :followed_users, dependent: :destroy

  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :comments

  has_one_attached :avatar

  validates :username, uniqueness: true

  before_create :set_default_avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]


  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.username = auth.info.name
      user.image_url = auth.info.image
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def set_default_avatar
    self.image_url ||= 'default_avatar.jpg'
  end

  def avatar_or_url
    avatar.attached? ? avatar : image_url.presence || 'default_avatar.jpg'
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @user = User.find(params[:id])
  end

  def user_posts
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def accepted?(user1, user2)
    Fellowship.find_by(follower_id: user2.id, followee_id: user1.id, status: 'accepted').present?
  end

  def onhold?(user1, user2)
    Fellowship.find_by(follower_id: user2.id, followee_id: user1.id, status: 'onhold').present?
  end
end

app/views/users/followers.html.erb
<%= turbo_frame_tag 'profile_extension' do %>

  <h1>Followers</h1>

  <% @followers.each do |user| %>
    
      <div class="post-card flex py-5 my-2 dark:bg-gray-900 border dark:hover:bg-gray-800">

        <%= link_to profile_path(user), data: { turbo_frame: "_top" } do %>
          <span class= "flex items-center">
            <h5 class="p-5 text-xl font-medium dark:text-white"><%= user.username %></h5>
          </span>
        <% end %>

        <% unless user == current_user %>
          <div class="flex items-center">

            <% if following?(user) %>
              <%= button_to "Unfollow", user_fellowships_path(user), class: "inline-flex items-center btn-primary dark:bg-gray-900 dark:hover:bg-gray-950" %>
            <% else %>
              <%= button_to "Follow", user_fellowships_path(user), class: "inline-flex items-center btn-primary" %>
            <% end %>

          </div>
        <% end %>

      </div>

  <% end %>

<% end %>

app/views/users/following.html.erb
<%= turbo_frame_tag 'profile_extension' do %>

  <h1>Following</h1>

  <% @following.each do |user| %>
    
      <div class="post-card flex py-5 my-2 dark:bg-gray-900 border dark:hover:bg-gray-800">

        <%= link_to profile_path(user), data: { turbo_frame: "_top" } do %>
          <span class= "flex items-center">
            <h5 class="p-5 text-xl font-medium dark:text-white"><%= user.username %></h5>
          </span>
        <% end %>

        <% if user == current_user %>
          <div class="flex items-center">
            <%= button_to "Remove follower", user_fellowships_path(user), class: "inline-flex items-center btn-primary dark:bg-gray-900 dark:hover:bg-gray-950" %>
          </div>
        <% end %>

      </div>

  <% end %>

<% end %>

app/views/users/profile.html.erb
<%= link_to '<- Back to home', root_path, class:"link-primary mb-10 w-fit" %>

<div class="border rounded-lg dark:bg-gray-800 dark:border-gray-700">


    <div class="flex justify-end px-4 pt-4">

      <% if current_user == @user %>
        <%= link_to edit_user_registration_path do %>

          <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
            <g stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
              <path d="M19 11V9a1 1 0 0 0-1-1h-.757l-.707-1.707.535-.536a1 1 0 0 0 0-1.414l-1.414-1.414a1 1 0 0 0-1.414 0l-.536.535L12 2.757V2a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v.757l-1.707.707-.536-.535a1 1 0 0 0-1.414 0L2.929 4.343a1 1 0 0 0 0 1.414l.536.536L2.757 8H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h.757l.707 1.707-.535.536a1 1 0 0 0 0 1.414l1.414 1.414a1 1 0 0 0 1.414 0l.536-.535L8 17.243V18a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-.757l1.707-.708.536.536a1 1 0 0 0 1.414 0l1.414-1.414a1 1 0 0 0 0-1.414l-.535-.536.707-1.707H18a1 1 0 0 0 1-1Z"/>
              <path d="M10 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
            </g>
          </svg>

        <% end %>
      <% end %>

    </div>




    <%= turbo_frame_tag 'profile_stats' do %>
      <div class="flex flex-col items-center pb-10">

        <%= image_tag @user.avatar_or_url, alt: 'User Avatar', class: 'profile-avatar' %>
        <h5 class="mb-1 text-xl font-medium dark:text-white"><%= @user.username %></h5>

        <div class="inline-flex rounded-md mt-1">

          <%= link_to user_posts_path,
                      data: { turbo_frame: "profile_extension" },
                      class: "profile-stats" do %>

            Posts: <%= @user.posts.count %>
          <% end %>

          <%= link_to user_fellowships_path(@user, partial: 'followers'),
                      data: { turbo_frame: "profile_extension" },
                      class: "profile-stats" do %>

            Followers: <%= @user.following_users.where(status: 'accepted').count %>
          <% end %>

          <%= link_to user_fellowships_path(@user, partial: 'following'),
                      data: { turbo_frame: "profile_extension" },
                      class: "profile-stats" do %>

            Following: <%= @user.followed_users.where(status: 'accepted').count %>
          <% end %>

        </div>

        <% if current_user != @user %>
            <div class="flex mt-6">

              <% if accepted?(@user, current_user)  %>
                <%= button_to "Unfollow", 
                              user_fellowship_path(@user, 
                                                Fellowship.find_by(follower_id: current_user, followee_id: @user)), 
                              method: :delete, 
                              class: "btn-primary dark:bg-gray-900 dark:hover:bg-gray-950" %>
              <% elsif onhold?(@user, current_user) %>
                <%= button_to "Requested", 
                              user_fellowship_path(@user, 
                                                Fellowship.find_by(follower_id: current_user, followee_id: @user)), 
                              method: :delete, 
                              class: "btn-primary dark:bg-gray-900 dark:hover:bg-gray-950" %>
              <% else %>
                <%= button_to "Follow", 
                              user_fellowships_path(@user), 
                              class: "btn-primary" %>
              <% end %>

            </div>
        <% end %>

      </div>
  <% end %>

</div>


<div class="mt-5">
  <%= turbo_frame_tag "profile_extension" do %>
    <%= render @user.posts %>
  <% end %>
</div>

app/views/users/user_posts.html.erb
<%= turbo_frame_tag 'profile_extension' do %>
    <%= render @user.posts %>
<% end %>