config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/profile', to: 'users#profile', as: :profile
  get 'users/:id/posts', to: 'users#user_posts', as: :user_posts

  resources :users, only: [] do
    resources :fellowships, only: [:index, :create, :destroy, :update]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"

  resources :posts do
    resources :comments
    resources :likes, only: [:create]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  default_scope { order(created_at: :desc) }

  has_one_attached :image

  validates :body, length: { maximum: 280 }

  validate :body_or_image_presence

  validate :upload_is_image

  private

  def upload_is_image
    unless image and image.content_type =~ /^image\/(jpeg|pjpeg|gif|png|bmp)$/
      errors.add(:upload, "is not a valid image") if image.attached?
    end
  end

  def body_or_image_presence
    errors.add(:base, 'Post must have either body or image') unless body.present? || image.attached?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:body, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def liked?(post)
    post.likes.exists?(user_id: current_user.id)
  end
end

app/views/posts/_form.html.erb
<%= form_with model: Post.new do |form| %>

  <div class="mb-10">

    <% if @post.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li style="color: red"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>


    <%= form.text_area :body, 
                       class: "input-text-area", 
                       input_html: { autofocus: true }, 
                       placeholder: "What's on your mind?",
                       rows: 4 %><br>
    
    <div class="block justify-end">
      <%= form.file_field :image, class:"
                                  block w-full text-sm text-slate-500
                                  file:mr-4 file:py-2 file:px-4
                                  file:rounded-lg file:border-0
                                  file:text-sm file:font-semibold
                                  file:bg-violet-50 file:text-violet-700
                                  hover:file:bg-violet-200 file:mb-3" %>
    </div>

    <%= form.submit class: "btn-primary cursor-pointer" %>
    <%= link_to "Cancel", 
                posts_path, 
                data: { turbo_frame: "_top" },
                class: "btn-primary bg-red-500 hover:bg-red-600" %>
    
  </div>

<% end %>

app/views/posts/_post.html.erb
  <div class="justify-center flex-1">
    <div class="w-fit dark:hover:bg-gray-800 rounded-lg p-1">
      <%= link_to profile_path(post.user), data: {turbo_frame: "_top"} do %>
        <span class="flex items-center gap-2.5">
          <%= image_tag post.user.avatar_or_url, alt: 'User Avatar', class: 'user-avatar' %>
          <%= post.user.username %>
        </span>
      <% end %>
    </div>

    <% if current_page?(post_path(post)) %>
      <div class="post-card flex-1 py-10 my-1">
        <%= image_tag post.image if post.image.attached? %>
        <p class="post-body break-all"><%= post.body %></p>
      </div>
    <% else %>
      <%= link_to post_path(post), 
                  data: {turbo_frame: "_top"},
                  class: "flex-1 w-max" do %>
        <div class="post-card flex-1 py-10 my-1">
          <%= image_tag post.image if post.image.attached? %>
          <p class="post-body break-all"><%= post.body %></p>
        </div>
      <% end %>
    <% end %>

    <%= button_to post_likes_path(post), class: "flex-none" do %>
      <svg class="w-6 h-6 <%= liked?(post) ? "#{'text-red-500'}" : "#{'text-gray-400'}" %>" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
        <path d="M17.947 2.053a5.209 5.209 0 0 0-3.793-1.53A6.414 6.414 0 0 0 10 2.311 6.482 6.482 0 0 0 5.824.5a5.2 5.2 0 0 0-3.8 1.521c-1.915 1.916-2.315 5.392.625 8.333l7 7a.5.5 0 0 0 .708 0l7-7a6.6 6.6 0 0 0 2.123-4.508 5.179 5.179 0 0 0-1.533-3.793Z"/>
      </svg>
      <%= post.likes.count %>
    <% end %>
  </div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts", partial: 'posts/post', locals: { post: @post } %>
<%= turbo_stream.update Post.new, "" %>

app/views/posts/index.html.erb
<%= turbo_frame_tag Post.new %>

<%= turbo_frame_tag "posts" do %>

    <% @posts.each do |post| %>

      <div class= "justify-center mb-2">
        <div class="flex gap-2 items-center">

          <%= render post %>
          
        </div>
      </div>

    <% end %>

<% end %>

app/views/posts/new.html.erb
<%= turbo_frame_tag @post do %>
  <%= render 'form', post: @post %>
<% end %>

app/views/posts/show.html.erb
<%= link_to '<- Back', :back, class:"link-primary mb-10 w-fit" %>

<div class="justify-center gap-2.5">

  <div class="flex items-center gap-2">

    <%= render @post %>

  </div>

  <%= render partial: "comments/form", locals: {post: @post} %>

  <%= render @post.comments %>
</div>